server:
  port: 8081 # 端口号

spring:
  application:
    name: dubbo-consumer # 应用名


dubbo:
  protocol:
    name: dubbo # dubbo 协议
    port: 20880
  service:
    version: 1.0.0 # 自定义dubbo服务版本
  registry:
    address: zookeeper://127.0.0.1:2181/dubbo
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
